version: "3.5"

services:
  webserver:
    build:
      context: .
      dockerfile: docker/ci/nginx/Dockerfile
    container_name: mdshop-webserver-all
    volumes:
      - '../mdshop-ui-admin:/application/ui-admin'
    ports:
      - 80:80
    networks:
      - mdshop-net
networks:
  mdshop-net:
    name: mdshop-net
    driver: bridge
